spring.application.name=projectDemo


#connect db
spring.datasource.url=jdbc:postgresql://localhost:5433/dataDemo
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.show-sql=true

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update



#config session
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always


#set time
spring.session.timeout=5m


#Loggin config
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.net.guides=DEBUG


#logging.level.root=INFO
#logging.file=logs/mylog.log


#activeMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.activemq.packages.trust-all=true
activemq.destination=store

